PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ch: <https://schema.ld.admin.ch/>
PREFIX lindas: <https://lindas.admin.ch/>
CONSTRUCT {
  ?geometry geo:asWKT ?wkt .
}
WHERE {
  ?placeInTime a geo:Feature ; geo:defaultGeometry ?geometry ;
    dcterms:issued "2026-01-01"^^xsd:date ;
    dcterms:isVersionOf / schema:about ?place .
  ?geometry geo:asWKT ?wkt .
  SERVICE lindas:query {
    ?place a ?type .
    VALUES ?type { ch:Canton ch:District ch:Municipality }
  }
}
LIMIT 1