PREFIX cube: <https://cube.link/>
PREFIX schema: <http://schema.org/>
PREFIX : <https://agriculture.ld.admin.ch/crops/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
CONSTRUCT {
    ?node a :CultivationType ;
        schema:name ?name ;
        schema:description ?description ;
        :partOf ?parent ;
        :botanicalPlant ?botanicalPlant ;
        :hasMembership ?membership ;
        :hasAttribute ?attribute .

    ?attribute :attributeType ?attributeType ;
        :attributeValue ?attributeValue .

    ?attributeType schema:name ?attributeTypeName .
    ?attributeValue schema:name ?attributeValueName .
    ?botanicalPlant :taxonName ?taxonName ;
        :eppo ?eppoCode .
    ?membership schema:identifier ?identifier ;
        schema:name ?membershipName ;
        schema:validFrom ?validFrom ;
        schema:validTo ?validTo .
}
WHERE {
    ?node rdfs:subClassOf* :Cultivation .
    ?node schema:name ?name .
    FILTER(LANG(?name) = "de")
    OPTIONAL {
        ?node rdfs:subClassOf ?parent .
    }
    OPTIONAL {
        ?node schema:description ?description .
        FILTER(LANG(?description) = "de")
    }
    OPTIONAL {
        ?node :botanicalPlant ?botanicalPlant .
        OPTIONAL { ?botanicalPlant :taxonName ?taxonName . }
        OPTIONAL { ?botanicalPlant :eppo ?eppoCode . }
    }
    OPTIONAL {
        ?membership :cultivationType ?node .
        ?membership a cube:Observation .
        ?membership schema:name ?membershipName .
        ?membership schema:identifier ?identifier .
        OPTIONAL { ?membership schema:validFrom ?validFrom . }
        OPTIONAL { ?membership schema:validTo ?validTo . }
    }
    OPTIONAL {
        VALUES ?attributeType { :intensity :purpose :cultivationMethod }
        ?node ?attributeType ?attributeeValue .
        BIND(BNODE() AS ?attribute)
        ?attributeType schema:name ?attributeTypeName .
        FILTER(LANG(?attributeTypeName) = "de")
        ?attributeValue schema:name ?attributeValueName .
        FILTER(LANG(?attributeValueName) = "de")
    }
}