PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

INSERT {
  ?instance rdf:type ?parentClass .
}
WHERE {
  ?instance rdf:type ?childClass .
  ?childClass rdfs:subClassOf+ ?parentClass .
  FILTER (!isBlank(?childClass))
  FILTER (!isBlank(?parentClass))
}